---

- name: Get ARP information
  hosts: all
  gather_facts: false

  tasks:
  - name: configure the login banner
    ios_banner:
      banner: login
      text: |
        this is my login banner
        that contains a multiline
        string
      state: present
    #register: print_output

    #- debug: var=print_output.stdout_lines
