---

- name: Get ARP information
  hosts: all
  gather_facts: false

  tasks:
  - name: Merge provided configuration with device configuration
    ios_vlans:
      config:
        - name: Vlan_10
          vlan_id: 10
          state: active
          shutdown: disabled
        - name: Vlan_20
          vlan_id: 20
          mtu: 610
          state: active
          shutdown: enabled
        - name: Vlan_30
          vlan_id: 30
          state: suspend
          shutdown: enabled
      state: merged
      #  register: print_output
      # - debug: var=print_output.stdout_lines
